import * as PrismaInternals from "@prisma/internals"
import { execFileSync } from "child_process"
import * as fs from "fs-jetpack"
import * as Path from "path"
import * as ts from "typescript"
import { generateAndEmit } from "../../src/generator"
import {
  prismaMajor,
  toInstalledPrismaSyntax,
  toNewClientGeneratorSyntax,
} from "../__helpers__/prismaSchemaCompat"

/**
 * Same pipeline as `typecheck.test.ts`, but against Prisma 7's new
 * `prisma-client` generator instead of the legacy `prisma-client-js` one.
 *
 * This is what caught a real regression: `prisma-client` always requires a
 * custom `output` and emits its main entry point as `client.ts` directly
 * inside that directory, with no `index.ts`/`package.json` for Node/TS to
 * resolve implicitly. `getRelativePrismaClientPath` assumed an implicitly
 * resolvable directory whenever the output wasn't the default
 * `node_modules/@prisma/client` location, so the import it generated
 * (`import * as PrismaLib from "../client"`) failed to resolve for this
 * generator — even though the exact same schema, generated with
 * `prisma-client-js` and a custom `output`, worked fine.
 *
 * Only runs when Prisma 7+ is installed, since `prisma-client` doesn't
 * exist as a generator provider before that.
 */
const itIfPrisma7 = prismaMajor >= 7 ? it : it.skip

itIfPrisma7(
  "generates code that type-checks against a real Prisma Client generated by the new `prisma-client` generator",
  async () => {
    const rootDir = Path.join(__dirname, "..", "..")
    const schemaPath = Path.join(__dirname, "schema.prisma")
    const rawSchema = await fs.readAsync(schemaPath)

    if (!rawSchema) {
      throw new Error(`Unable to read fixture schema at "${schemaPath}".`)
    }

    const schema = toNewClientGeneratorSyntax(
      toInstalledPrismaSyntax(rawSchema)
    )

    const dir = Path.join(
      rootDir,
      ".e2e-tmp",
      `${Date.now()}-${Math.random().toString(36).slice(2)}`
    )
    fs.dir(dir)
    const tmpSchemaPath = Path.posix.join(dir, "schema.prisma")
    const prismaClientPath = Path.posix.join(dir, "./client")
    const dirOut = Path.posix.join(dir, "./crud")

    try {
      await fs.writeAsync(tmpSchemaPath, schema)

      execFileSync(
        process.execPath,
        [
          require.resolve("prisma/build/index.js"),
          "generate",
          "--schema",
          tmpSchemaPath,
        ],
        {
          cwd: rootDir,
          stdio: "pipe",
          env: { ...process.env, PRISMA_GENERATE_SKIP_AUTOINSTALL: "true" },
        }
      )

      const dmmf = await PrismaInternals.getDMMF({ datamodel: schema })

      await generateAndEmit(dmmf, dirOut, prismaClientPath)

      const consumerSource = `
import { objectType } from "nexus"
import { ClientCRUD } from "./index"

export const ClientType = objectType({
  name: "Client",
  definition(t) {
    t.field(ClientCRUD.Model.id)
    t.field(ClientCRUD.Model.name)
    t.field(ClientCRUD.Model.age)
    t.field(ClientCRUD.Model.userId)
    t.field(ClientCRUD.Model.user)
    t.field(ClientCRUD.Model.contacts)
  },
})
`
      await fs.writeAsync(
        Path.posix.join(dirOut, "consumer.ts"),
        consumerSource
      )

      const nexusDir = Path.dirname(require.resolve("nexus/package.json"))
      const graphqlDir = Path.dirname(require.resolve("graphql/package.json"))

      const program = ts.createProgram({
        rootNames: [
          Path.posix.join(dirOut, "index.ts"),
          Path.posix.join(dirOut, "consumer.ts"),
        ],
        options: {
          target: ts.ScriptTarget.ES2018,
          lib: ["lib.es2018.d.ts"],
          module: ts.ModuleKind.CommonJS,
          moduleResolution: ts.ModuleResolutionKind.NodeJs,
          strict: true,
          esModuleInterop: true,
          skipLibCheck: true,
          noEmit: true,
          baseUrl: rootDir,
          paths: {
            "nexus-prisma-crud": [Path.join(rootDir, "src", "index.ts")],
            nexus: [nexusDir],
            graphql: [graphqlDir],
          },
        },
      })

      const errors = ts
        .getPreEmitDiagnostics(program)
        .filter((d) => d.category === ts.DiagnosticCategory.Error)

      if (errors.length > 0) {
        const message = ts.formatDiagnosticsWithColorAndContext(errors, {
          getCurrentDirectory: () => dirOut,
          getCanonicalFileName: (f) => f,
          getNewLine: () => "\n",
        })
        throw new Error(message)
      }
    } finally {
      fs.remove(dir)
    }
  },
  60000
)
